# Settings
baseurl = "/"
languageCode = "en-us"
title = "MADE BY HUMAN RACE"
theme = "phugo"
googleAnalytics = "UA-41139230-14"

[params]

    # Meta
    description = "Made by Human Race - Photos"
    author = ""
    keywords = "photogallery, hugo, photoblog"

    # Headerbar links
    # Do not put here too many links,
    # it will break mobile appearance

    [[params.header.links]]
    name = "About"
    url = "#footer"
    icon = "fa-info-circle"

    # Footer panel

    [params.footer.paragraph]
    headline = "About this"
    text = "just trying a new, free and opensources way to display pictures. About privacy, this site hosts no ads, record and sell no data"

    [params.footer.social]
    headline = "Follow me"

    [[params.footer.social.links]]
    label = "Twitter"
    url = "https://twitter.com/MadeByHumanRace"
    icon = "fa-twitter"

    [[params.footer.social.links]]
    label = "Instagram"
    url = "https://www.instagram.com/madebyhumanrace/"
    icon = "fa-instagram"

    # Contact form

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'realEmail' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    [params.footer.contact]
    hide = false # Set this to true if you don't want to have a contact form on your site
    realEmail = "mail@madebyhumanrace.com"
    headline = "Get in touch"
    buttonText = "Send"
    resetText = "Reset"

    # 'warning' defines error messages for invalid inputs
    [params.footer.contact.name]
    text = "Name *"
    warning = "Please, enter your name"

    [params.footer.contact.email]
    text = "Email *"
    warning = "Please, enter your email."

    [params.footer.contact.message]
    text = "Message *"
    warning = "Please, enter your message"

    # Copyright
    [params.footer.copyright]
    name = "Your name"
